CREATE TABLE IF NOT EXISTS GIF (
    IDINT AUTO_INCREMENT PRIMARY KEY
    gifName VARCHAR(50) NOT NULL,
    Score FLOAT NOT NULL,
    URL VARCHAR(255) NOT NULL
    fID INT NOT NULL,
    CONSTRAINT fid
    FOREGEIN KEY (fID)
    REFERENCES Film (fID)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
    ) ENGINE = InnoDB
